/**
 * @description This class is used for handling Web-to-Case functionality.
 * @Author Surendranath Reddy
 * @Author Subba Reddy Venkata
 * @Author Sprutiraj Panda
 * @Author Sravani Bandaru
 * @Last Modified By Subba Reddy Venkata
 * @Last Modified By Sprutiraj Panda
 * @Last Modified On 20/04/2023
 * @Modification Log:
 * Ver    Date          Author        Last Modification
 * 1.0    26/04/2023    Sprutiraj     Initial Version
 *                        Subba Reddy Venkata
 **/
public without sharing class CaseController {
    //hfgkhjl
   
}